permalink: pretty

title: Will Jones
tagline:
url: http://sacharissa.co.uk
paginate: 1
baseurl: /
author:
  name: Will Jones
  url: https://twitter.com/lunarisbluemoon
  email: will@sacharissa.co.uk

gems:
- 'jekyll-paginate'

pages_list:
  CV: '/cv'
